#ifndef ARCH_ADDRESS_SPACE_INFO_H
#define ARCH_ADDRESS_SPACE_INFO_H


#define MPU_ENABLE_ADDRESS 0xefff3000

#define ATTACK_CAPABILITY_REGION_START 0x80000000
#define ATTACK_CAPABILITY_REGION_END 0x8fffffff

#endif